version: "3.4"

services:
  # App
  app:
    build: ./app
    container_name: app
    environment:
      LOG_LEVEL: DEBUG
      DI_PROFILE_ACTIVES: mysql,elasticsearch
      SQS_ENDPOINT_URL: http://localstack:4566
      SQS_REGION_NAME: ap-northeast-1
      SQS_QUEUE_URL: http://localhost:4566/000000000000/greeedy-queue
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: pass
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE_NAME: greeedy
      ELASTICSEARCH_HOSTNAME: elasticsearch
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      USER_DICTIONARY_PATH: extra/user_dictionary.txt
      SYNONYMS_PATH: extra/synonyms.txt
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
      - $HOME/.aws:/root/.aws

  # Amazon SQS
  localstack:
    container_name: localstack
    image: localstack/localstack:1.0.4
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      SERVICES: sqs  # Amazon SQS
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d:cached
      - $HOME/.aws:/root/.aws

  # Elasticsearch
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    env_file:
      - ./elasticsearch/.env
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
      - ./elasticsearch/synonyms.txt:/usr/share/elasticsearch/config/extra/synonyms.txt
      - ./elasticsearch/user_dictionary.txt:/usr/share/elasticsearch/config/extra/user_dictionary.txt

  # DB
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=greeedy
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql-volume:/var/lib/mysql

volumes:
  elasticsearch-volume:
    driver: 'local'
  mysql-volume:
    driver: 'local'