version: "3.4"

services:
  # App
  app:
    build: ./
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/

  # Amazon SQS
  localstack:
    container_name: localstack
    image: localstack/localstack:1.0.4
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      SERVICES: sqs  # Amazon SQS
    ports:
      - "4566:4566"
    volumes:
      - ./services/localstack/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d:cached
      - $HOME/.aws:/root/.aws

  # Elasticsearch
  elasticsearch:
    build: ./services/elasticsearch
    container_name: elasticsearch
    env_file:
      - ./services/elasticsearch/.env
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
      - ./services/elasticsearch/synonyms.txt:/usr/share/elasticsearch/config/extra/synonyms.txt
      - ./services/elasticsearch/user_dictionary.txt:/usr/share/elasticsearch/config/extra/user_dictionary.txt

  # DB
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=greeedy
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/conf.d:/etc/mysql/conf.d
      - mysql-volume:/var/lib/mysql

volumes:
  elasticsearch-volume:
    driver: 'local'
  mysql-volume:
    driver: 'local'