FROM public.ecr.aws/lambda/python:3.9

COPY app .

RUN yum install -y python3-devel mysql-devel gcc && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["start_app.handler"]